---
apiVersion: v1
kind: Service
metadata:
    name: worker-v1
spec: 
    selector:
        app: worker
    type: NodePort
    ports:
        - port: 4000
          targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: worker-deployment
    labels:
        app: worker
        version: v1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: worker
    template:
        metadata:
            labels:
                app: worker
        spec:
            containers:
                - name: worker-v1
                  image: gcr.io/optimistic-yew-208712/worker:0.0.5
                  ports:
                      - containerPort: 4000
